title: "David L. Vargas"
author: "David L. Vargas"
description: "David L. Vargas | Personal Site "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About me", file: "README.md"}
  - {title: "Research +", file: "Research.md"}
  - {title: "CV", url: "https://www.dropbox.com/s/xxsyzlb5d1v83u8/ENG_CV.pdf?dl=0"}
  
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:davidvar@iadb.org"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/DavidLVargasM"}
  # - {title: Github, icon: github, url: "https://github.com/davidlvargas"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-twitter-plugin
